spring:
  application:
    name: ${APP_NAME:discovery-service}
server:
  port: ${PORT:8761}
eureka:
  client:
    service-url:
      defaultZone: ${DEFAULT_ZONE:http://localhost:8761/eureka/}
    fetch-registry: ${FETCH_REGISTRY:false}
    register-with-eureka: ${REGISTER_WITH_EUREKA:false}
  instance:
    hostname: ${HOSTNAME:localhost}
    prefer-ip-address: ${PREFER_IP_ADDRESS:true}
  server:
    enableSelfPreservation: true
    renewalPercentThreshold: 0.5
    maxThreadsForPeerReplication: ${MAX_THREAD_FOR_PEER_REPLICATION:3}
    waitTimeInMsWhenSyncEmpty: 0